name: Build and Package DEB

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libx11-dev zenity xprintidle dpkg-dev
    - name: Build binary
      run: gcc -O2 -Wall screen_watcher.c -o screen_watcher $(pkg-config --cflags --libs x11)
    - name: Create DEB package structure
      run: |
        mkdir -p pkg/usr/bin
        cp screen_watcher pkg/usr/bin/
        mkdir -p pkg/DEBIAN
        cat <<EOF > pkg/DEBIAN/control
Package: timer30
Version: 1.0.0
Section: utils
Priority: optional
Architecture: amd64
Depends: zenity, xprintidle, libx11-6
Maintainer: Your Name <your@email.com>
Description: timer30 - Stay aware of your computer usage time.
EOF
        mkdir -p pkg/usr/share/applications
        cat <<EOF > pkg/usr/share/applications/timer30.desktop
[Desktop Entry]
Type=Application
Name=timer30
Exec=/usr/bin/screen_watcher
X-GNOME-Autostart-enabled=true
Comment=Stay aware of your computer usage time.
EOF
    - name: Build DEB
      run: dpkg-deb --build pkg timer30.deb
    - name: Upload DEB artifact
      uses: actions/upload-artifact@v4
      with:
        name: timer30.deb
        path: timer30.deb
